#ifndef _RADIANT_LIB_MARSHALL_H
#define _RADIANT_LIB_MARSHALL_H

#define BEGIN_RADIANT_MARSHALL_NAMESPACE  namespace radiant { namespace marshall {
#define END_RADIANT_MARSHALL_NAMESPACE    } }

BEGIN_RADIANT_MARSHALL_NAMESPACE

class Convert;

END_RADIANT_MARSHALL_NAMESPACE

#endif // _RADIANT_LIB_MARSHALL_H
