#ifndef _BUILD_NUMBER_H
#define _BUILD_NUMBER_H

/*
 * This is not the file you're probably looking for.  It exists only to get
 * the build to compile in developer builds.  The actual file used by official
 * builds (which probably has the defines your looking for), is generated by
 * the official build script and placed into the build directory (which is
 * included before this file in the include path).
 *
 * Modifying anything in here is almost certainly a mistake.  You have been
 * warned!
 */

#define PRODUCT_IDENTIFIER          "stonehearth"
#define PRODUCT_NAME                "Stonehearth Development Build"
#define PRODUCT_MAJOR_VERSION       1
#define PRODUCT_MINOR_VERSION       2
#define PRODUCT_PATCH_VERSION       3
#define PRODUCT_BUILD_NUMBER        45678
#define PRODUCT_BRANCH              "#branch#"
#define PRDOCUT_REVISION            "#revision#"
#define PRODUCT_VERSION_STR         "1.2.3"
#define PRODUCT_FILE_VERSION_STR    "1.2.3.45678"

#endif // _BUILD_NUMBER_H
