#ifndef _RADIANT_CHROMIUM_NAMESPACE_H
#define _RADIANT_CHROMIUM_NAMESPACE_H

#define BEGIN_RADIANT_CHROMIUM_NAMESPACE  namespace radiant { namespace chromium {
#define END_RADIANT_CHROMIUM_NAMESPACE    } }

#define RADIANT_CHROMIUM_NAMESPACE    ::radiant::chromium

#define IN_RADIANT_CHROMIUM_NAMESPACE(x) \
   BEGIN_RADIANT_CHROMIUM_NAMESPACE \
   x  \
   END_RADIANT_CHROMIUM_NAMESPACE

#endif //  _RADIANT_CHROMIUM_NAMESPACE_H
