#ifndef _RADIANT_OM_TRACE_CATEGORIES_H
#define _RADIANT_OM_TRACE_CATEGORIES_H

#include "namespace.h"

BEGIN_RADIANT_OM_NAMESPACE

enum TraceCategories {
   OM_TRACES = 1000,
};

END_RADIANT_OM_NAMESPACE

#endif //  _RADIANT_OM_TRACE_CATEGORIES_H
