#ifndef _RADIANT_HORDE3D_NAMESPACE_H
#define _RADIANT_HORDE3D_NAMESPACE_H

#define BEGIN_RADIANT_HORDE3D_NAMESPACE  namespace radiant { namespace horde3d {
#define END_RADIANT_HORDE3D_NAMESPACE    } }

#define RADIANT_HORDE3D_NAMESPACE    ::radiant::horde3d

#define IN_RADIANT_HORDE3D_NAMESPACE(x) \
   BEGIN_RADIANT_HORDE3D_NAMESPACE \
   x  \
   END_RADIANT_HORDE3D_NAMESPACE

#endif //  _RADIANT_HORDE3D_NAMESPACE_H
