local commands = {
   WAIT_REALTIME     = 'WAIT_REALTIME',
   SELECT_ENTITY     = 'SELECT_ENTITY',
   CLICK_DOM_ELEMENT = 'CLICK_DOM_ELEMENT',
   CLICK_TERRAIN     = 'CLICK_TERRAIN',
}

return commands
