#ifndef _RADIANT_LUA_FORWARD_DEFINES_H
#define _RADIANT_LUA_FORWARD_DEFINES_H

#include "namespace.h"

BEGIN_RADIANT_LUA_NAMESPACE

class ScriptHost;

END_RADIANT_LUA_NAMESPACE

#endif // _RADIANT_LUA_FORWARD_DEFINES_H
