#ifndef _RADIANT_CLIENT_NAMESPACE_H
#define _RADIANT_CLIENT_NAMESPACE_H

#define BEGIN_RADIANT_CLIENT_NAMESPACE  namespace radiant { namespace client {
#define END_RADIANT_CLIENT_NAMESPACE    } }

#define RADIANT_CLIENT_NAMESPACE    ::radiant::client

#define IN_RADIANT_CLIENT_NAMESPACE(x) \
   BEGIN_RADIANT_CLIENT_NAMESPACE \
   x  \
   END_RADIANT_CLIENT_NAMESPACE

#endif //  _RADIANT_CLIENT_NAMESPACE_H
