#ifndef _RADIANT_SIMULATION_NAMESPACE_H
#define _RADIANT_SIMULATION_NAMESPACE_H

#define BEGIN_RADIANT_SIMULATION_NAMESPACE  namespace radiant { namespace simulation {
#define END_RADIANT_SIMULATION_NAMESPACE    } }

#define RADIANT_SIMULATION_NAMESPACE    ::radiant::simulation

#define IN_RADIANT_SIMULATION_NAMESPACE(x) \
   BEGIN_RADIANT_SIMULATION_NAMESPACE \
   x  \
   END_RADIANT_SIMULATION_NAMESPACE

BEGIN_RADIANT_SIMULATION_NAMESPACE

class Simulation;
class Job;
class Task;
class Path;
class PathFinder;
class PathFinderSrc;
class PathFinderDst;
class BfsPathFinder;
class AStarPathFinder;
class DirectPathFinder;
class EntityJobScheduler;
class ApplyFreeMotionTask;

DECLARE_SHARED_POINTER_TYPES(Path)
DECLARE_SHARED_POINTER_TYPES(PathFinder)
DECLARE_SHARED_POINTER_TYPES(PathFinderSrc)
DECLARE_SHARED_POINTER_TYPES(PathFinderDst)
DECLARE_SHARED_POINTER_TYPES(BfsPathFinder)
DECLARE_SHARED_POINTER_TYPES(AStarPathFinder)
DECLARE_SHARED_POINTER_TYPES(DirectPathFinder)
DECLARE_SHARED_POINTER_TYPES(EntityJobScheduler)
DECLARE_SHARED_POINTER_TYPES(ApplyFreeMotionTask)

END_RADIANT_SIMULATION_NAMESPACE

#endif //  _RADIANT_SIMULATION_NAMESPACE_H
