#ifndef _RADIANT_SIMULATION_NAMESPACE_H
#define _RADIANT_SIMULATION_NAMESPACE_H

#define BEGIN_RADIANT_SIMULATION_NAMESPACE  namespace radiant { namespace simulation {
#define END_RADIANT_SIMULATION_NAMESPACE    } }

#define RADIANT_SIMULATION_NAMESPACE    ::radiant::simulation

#define IN_RADIANT_SIMULATION_NAMESPACE(x) \
   BEGIN_RADIANT_SIMULATION_NAMESPACE \
   x  \
   END_RADIANT_SIMULATION_NAMESPACE

BEGIN_RADIANT_SIMULATION_NAMESPACE

class Simulation;
class Job;
class Task;
class PathFinder;
class EntityJobScheduler;

DECLARE_SHARED_POINTER_TYPES(PathFinder)
DECLARE_SHARED_POINTER_TYPES(EntityJobScheduler)

END_RADIANT_SIMULATION_NAMESPACE

#endif //  _RADIANT_SIMULATION_NAMESPACE_H
