#ifndef _RADIANT_SIMULATION_TRACE_CATEGORIES_H
#define _RADIANT_SIMULATION_TRACE_CATEGORIES_H

#include "namespace.h"

BEGIN_RADIANT_SIMULATION_NAMESPACE

enum TraceCategories {
   PATHFINDER_TRACES,
};

END_RADIANT_SIMULATION_NAMESPACE

#endif //  _RADIANT_SIMULATION_TRACE_CATEGORIES_H
