#ifndef _RADIANT_CRASH_REPORTER_CLIENT_NAMESPACE_H
#define _RADIANT_CRASH_REPORTER_CLIENT_NAMESPACE_H

#define BEGIN_RADIANT_CRASH_REPORTER_CLIENT_NAMESPACE  namespace radiant { namespace crash_reporter { namespace client {
#define END_RADIANT_CRASH_REPORTER_CLIENT_NAMESPACE    } } }

#endif // _RADIANT_CRASH_REPORTER_CLIENT_NAMESPACE_H
