#ifndef _RADIANT_AUDIO_NAMESPACE_H
#define _RADIANT_AUDIO_NAMESPACE_H

#define BEGIN_RADIANT_AUDIO_NAMESPACE  namespace radiant { namespace audio {
#define END_RADIANT_AUDIO_NAMESPACE    } }

BEGIN_RADIANT_AUDIO_NAMESPACE

class InputStream;

END_RADIANT_AUDIO_NAMESPACE

#endif //  _RADIANT_AUDIO_NAMESPACE_H
