#ifndef _RADIANT_CRASH_REPORTER_SERVER_NAMESPACE_H
#define _RADIANT_CRASH_REPORTER_SERVER_NAMESPACE_H

#define BEGIN_RADIANT_CRASH_REPORTER_SERVER_NAMESPACE  namespace radiant { namespace crash_reporter { namespace server {
#define END_RADIANT_CRASH_REPORTER_SERVER_NAMESPACE    } } }

#endif // _RADIANT_CRASH_REPORTER_SERVER_NAMESPACE_H
