#ifndef _RADIANT_LIB_JSON_CSG_CSG_JSON_H
#define _RADIANT_LIB_JSON_CSG_CSG_JSON_H

#include "csg/namespace.h"
#include "lib/json/namespace.h"
#include "lib/json/macros.h"

BEGIN_RADIANT_JSON_NAMESPACE

DECLARE_JSON_CODEC_TEMPLATES(csg::Point1)
DECLARE_JSON_CODEC_TEMPLATES(csg::Point3)
DECLARE_JSON_CODEC_TEMPLATES(csg::Point1f)
DECLARE_JSON_CODEC_TEMPLATES(csg::Point2f)
DECLARE_JSON_CODEC_TEMPLATES(csg::Point3f)
DECLARE_JSON_CODEC_TEMPLATES(csg::Line1)
DECLARE_JSON_CODEC_TEMPLATES(csg::Rect2)
DECLARE_JSON_CODEC_TEMPLATES(csg::Rect2f)
DECLARE_JSON_CODEC_TEMPLATES(csg::Cube3)
DECLARE_JSON_CODEC_TEMPLATES(csg::Cube3f)
DECLARE_JSON_CODEC_TEMPLATES(csg::Transform)
DECLARE_JSON_CODEC_TEMPLATES(csg::Region3)
DECLARE_JSON_CODEC_TEMPLATES(csg::Ray3)
DECLARE_JSON_CODEC_TEMPLATES(csg::Quaternion)
DECLARE_JSON_CODEC_TEMPLATES(csg::Color3)
DECLARE_JSON_CODEC_TEMPLATES(csg::Color4)

END_RADIANT_JSON_NAMESPACE

#endif // _RADIANT_LIB_JSON_CSG_CSG_JSON_H
