#ifndef _RADIANT_RES_NAMESPACE_H
#define _RADIANT_RES_NAMESPACE_H

#define BEGIN_RADIANT_RES_NAMESPACE  namespace radiant { namespace res {
#define END_RADIANT_RES_NAMESPACE    } }

BEGIN_RADIANT_RES_NAMESPACE

class IModule;

END_RADIANT_RES_NAMESPACE

#endif //  _RADIANT_RES_NAMESPACE_H
