#ifndef _RADIANT_PHYSICS_NAMESPACE_H
#define _RADIANT_PHYSICS_NAMESPACE_H

#define BEGIN_RADIANT_PHYSICS_NAMESPACE  namespace radiant { namespace Physics {
#define END_RADIANT_PHYSICS_NAMESPACE    } }

#define RADIANT_PHYSICS_NAMESPACE    ::radiant::Physics

#define IN_RADIANT_PHYSICS_NAMESPACE(x) \
   BEGIN_RADIANT_PHYSICS_NAMESPACE \
   x  \
   END_RADIANT_PHYSICS_NAMESPACE

#endif //  _RADIANT_PHYSICS_NAMESPACE_H
