#ifndef _RADIANT_VOXEL_NAMESPACE_H
#define _RADIANT_VOXEL_NAMESPACE_H

#define BEGIN_RADIANT_VOXEL_NAMESPACE  namespace radiant { namespace voxel {
#define END_RADIANT_VOXEL_NAMESPACE    } }

#define RADIANT_VOXEL_NAMESPACE    ::radiant::voxel

#define IN_RADIANT_VOXEL_NAMESPACE(x) \
   BEGIN_RADIANT_VOXEL_NAMESPACE \
   x  \
   END_RADIANT_VOXEL_NAMESPACE

#endif //  _RADIANT_VOXEL_NAMESPACE_H
