local commands = {
   WAIT_REALTIME        = 'WAIT_REALTIME',
   MOVE_CAMERA          = 'MOVE_CAMERA',
   SELECT_ENTITY        = 'SELECT_ENTITY',
   CLICK_DOM_ELEMENT    = 'CLICK_DOM_ELEMENT',
   CLICK_WORLD_COORD    = 'CLICK_WORLD_COORD',
   SET_SELECT_XZ_REGION = 'SET_SELECT_XZ_REGION',
   SET_CAMERA_PATH_TYPE = 'SET_CAMERA_PATH_TYPE',
   STRESS_UI_PERFORMANCE_EASY = 'STRESS_UI_PERFORMANCE_EASY',
   STRESS_UI_PERFORMANCE_HARD = 'STRESS_UI_PERFORMANCE_HARD'
}

return commands
