#ifndef _RADIANT_DM_FORWARD_DEFINES_H
#define _RADIANT_DM_FORWARD_DEFINES_H

#include "dm.h"

BEGIN_RADIANT_DM_NAMESPACE

class Object;
class Store;

END_RADIANT_DM_NAMESPACE

#endif // _RADIANT_DM_FORWARD_DEFINES_H
