#ifndef _RADIANT_DM_NAMESPACE_H
#define _RADIANT_DM_NAMESPACE_H

#define BEGIN_RADIANT_DM_NAMESPACE  namespace radiant { namespace dm {
#define END_RADIANT_DM_NAMESPACE    } }

BEGIN_RADIANT_DM_NAMESPACE

class Tracker;

END_RADIANT_DM_NAMESPACE

#endif //  _RADIANT_DM_NAMESPACE_H
