#ifndef _RADIANT_DM_TRACE_CATEGORIES_H
#define _RADIANT_DM_TRACE_CATEGORIES_H

BEGIN_RADIANT_DM_NAMESPACE

enum TraceCategories {
   OBJECT_MODEL_TRACES,
   PATHFINDER_TRACES,
   RENDER_TRACES,
   RPC_TRACES,
   PLAYER_1_TRACES,
};

END_RADIANT_DM_NAMESPACE

#endif //  _RADIANT_DM_TRACE_CATEGORIES_H
