#ifndef _RADIANT_CLIENT_RENDERER_FORWARD_DEFINES_H
#define _RADIANT_CLIENT_RENDERER_FORWARD_DEFINES_H

#include "namespace.h"
#include "radiant_macros.h"

BEGIN_RADIANT_CLIENT_NAMESPACE

class RenderEntity;

DECLARE_SHARED_POINTER_TYPES(RenderEntity);

END_RADIANT_CLIENT_NAMESPACE

#endif // _RADIANT_CLIENT_RENDERER_FORWARD_DEFINES_H
