local ExecutionUnitV2 = require 'components.ai.execution_unit_v2'
local CompoundAction = class()

local NEXT_ID = 1

function CompoundAction:__init(action_unit, activities, think_output_placeholders)
   -- initialize metadata   
   self._log = radiant.log.create_logger('ai.compound_action')
   self._execution_unit = action_unit
   self._activities = activities
   self._think_output_placeholders = think_output_placeholders
   self._run_frames = {}
   self._think_frames = {}
   local action = self._execution_unit:get_action()
   action.name = action.name
   self.name = action.name
   self.does = action.does
   self.priority = action.priority
   self.weight = action.weight
   self.name = action.name
   self.args = action.args
   self.think_output = action.think_output
   self.version = 2
   
   self._id = NEXT_ID
   NEXT_ID = NEXT_ID + 1   
end

function CompoundAction:set_debug_route(debug_route)
   self._debug_route = debug_route .. ' ca:' .. tostring(self._id)
   local prefix = string.format('%s (%s)', self._debug_route, self.name)
   self._log:set_prefix(prefix)
   self._execution_unit:set_debug_route(self._debug_route)
end

function CompoundAction:start_thinking(ai, entity, args)
   self._ai = ai
   self._args = args
   assert(#self._run_frames == 0)
   assert(#self._think_frames == 0)
   self._previous_think_output = {}
   self._previous_frames = {}
   self._current_activity = 1
   
   -- compound actions are not allowed to think so calling short_circuit_thinking
   -- should put it into the ready state
   self._execution_unit:initialize(self._args)
   self._execution_unit:short_circuit_thinking()
   assert(self._execution_unit:get_state() == 'ready')
   
   -- now wait until all the chained actions are ready
   self:_start_processing_next_activity()
end

function CompoundAction:_start_processing_next_activity()
   local activity = self._activities[self._current_activity]
   local replaced = self:_replace_placeholders(activity.args)
   local frame = self._ai:spawn(activity.name, replaced)
   table.insert(self._think_frames, frame)
   
   radiant.events.listen(frame, 'state_changed', self, self._on_execution_frame_state_change)
   self._log:spam('CURRENT.location currently %s before thinking new frame', self._ai.CURRENT.location)
   frame:set_current_entity_state(self._ai.CURRENT)
   frame:start_thinking()
end

function CompoundAction:_on_execution_frame_state_change(frame, state)
   if state == 'ready' then
      assert(self._previous_frames)
      assert(self._previous_think_output)
      assert(self._current_activity ~= nil)
      self._previous_frames[frame] = true
      local think_output = frame:get_active_execution_unit():get_think_output()
      table.insert(self._previous_think_output, think_output)
      if self._current_activity < #self._activities then
         self._current_activity = self._current_activity + 1
         self:_start_processing_next_activity(self._ai)
      else
         -- use the ones specified in the template or the ones generated by our
         -- base action
         local think_output = self._args
         if self._think_output_placeholders then
            think_output = self:_replace_placeholders(self._think_output_placeholders)
         end
         self._ai:set_think_output(think_output)
      end
   elseif state == 'processing' then
      if self._previous_frames[frame] then
         self._ai:abort('execution frame became un-ready.  starting over.')
      end
   end
end

function CompoundAction:stop_thinking(ai, entity, ...)
   for i=#self._think_frames,1,-1 do
      local frame = self._think_frames[i]
      radiant.events.unlisten(frame, 'state_changed', self, self._on_execution_frame_state_change)      
      frame:stop_thinking()
   end  
   
   self._think_frames = {}
   self._previous_think_output = nil
   self._current_activity = nil
end


function CompoundAction:_replace_placeholders(args)
   local replaced  = {}
   for name, value in pairs(args) do
      if type(value) == 'table' and value.__placeholder then
         local result = value:__eval(self)
         if result == nil then
            self._ai:abort('placeholder %s failed to return a value in %s', tostring(value), self.name)
         end
         replaced[name] = result
      else
         replaced[name] = value
      end
   end
   return replaced
end

function CompoundAction:start()
   self._run_frames = self._think_frames
   self._think_frames = {}

   self._execution_unit:start()
   for i=1,#self._run_frames do
      self._run_frames[i]:start()
   end
end

function CompoundAction:run(ai, entity, ...)
   self._execution_unit:run()
   for i=1,#self._run_frames do
      -- stop each action immediately after it completes.
      -- this lets it release resources after they are no longer needed
      -- instead of waiting until the entire action sequence completes
      self._run_frames[i]:run()
      self._run_frames[i]:stop()
   end
   self._execution_unit:stop()
end

function CompoundAction:stop()
   for i=#self._run_frames,1,-1 do
      self._run_frames[i]:stop()
   end
   self._run_frames = {}
   self._execution_unit:stop()
end

function CompoundAction:_get_args()
   return self._args
end

function CompoundAction:_get_previous_think_output(rewind_offset)
   local index = #self._previous_think_output - rewind_offset + 1
   return self._previous_think_output[index]
end

function CompoundAction:_get_current_entity_state()
   return self._ai.CURRENT
end

return CompoundAction
